apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mcp-patcher
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: ClusterRole
  name: machine-config-pool-patcher
  apiGroup: rbac.authorization.k8s.io
